# Generated by Django 2.2 on 2020-05-18 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bad_type',
            new_name='bed_type',
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_full_name', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField(default=datetime.datetime(2020, 5, 18, 18, 36, 2, 446230))),
                ('end_datetime', models.DateTimeField(default=datetime.datetime(2020, 5, 18, 18, 36, 2, 446251))),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='hotel.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_full_name', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField(default=datetime.datetime(2020, 5, 18, 18, 36, 2, 445691))),
                ('end_datetime', models.DateTimeField(default=datetime.datetime(2020, 5, 18, 18, 36, 2, 445734))),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.Room')),
            ],
        ),
    ]
