# Generated by Django 2.2 on 2020-05-18 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200518_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 19, 13, 54, 505319)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 19, 13, 54, 505298)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 19, 13, 54, 505839)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 19, 13, 54, 505819)),
        ),
    ]
