# Generated by Django 2.2 on 2020-05-18 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20200518_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_modification',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 22, 2, 37, 71840)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 22, 2, 37, 72268)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 22, 2, 37, 72247)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 22, 2, 37, 72768)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 22, 2, 37, 72744)),
        ),
    ]
