# Generated by Django 2.2 on 2020-05-18 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20200518_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='last_modification',
        ),
        migrations.AddField(
            model_name='room',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 22, 2, 57, 713471)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 22, 2, 57, 713915)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 22, 2, 57, 713895)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 22, 2, 57, 714378)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 22, 2, 57, 714357)),
        ),
    ]
