# Generated by Django 2.2 on 2020-05-18 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20200519_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 1, 18, 27, 370810)),
        ),
        migrations.AddField(
            model_name='checkin',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 1, 18, 27, 371312)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 1, 18, 27, 370792)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 1, 18, 27, 370772)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 1, 18, 27, 371294)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 1, 18, 27, 371273)),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 1, 18, 27, 370367)),
        ),
    ]
