# Generated by Django 2.2 on 2020-05-18 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20200519_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 1, 39, 42, 488578)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 1, 39, 42, 488596)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 1, 39, 42, 488558)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='end_datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 1, 39, 42, 489109)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 1, 39, 42, 489126)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='start_datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 1, 39, 42, 489086)),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 1, 39, 42, 488170)),
        ),
    ]
