# Generated by Django 2.2 on 2020-05-18 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20200519_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 2, 5, 3, 720215)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 2, 5, 3, 720232)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 2, 5, 3, 720196)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='end_datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 2, 5, 3, 720695)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 2, 5, 3, 720711)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='start_datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 2, 5, 3, 720677)),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 2, 5, 3, 719848)),
        ),
    ]
